#!/bin/bash
clear

# --- NAGIIP colors ---
r='\033[1;91m'
g='\033[1;92m'
y='\033[1;93m'
c='\033[1;96m'
n='\033[1;0m'
E='\033[1;92m[\033[1;00m×\033[1;92m]\033[1;91m'

# Check Platform
if [ -d "/data/data/com.termux/files/usr/" ]; then
    DIR="$HOME/.termux"
else
    DIR="$HOME/.NAGIIP"
fi

USER_FILE="$DIR/usernames.txt"
ZSHRC="$HOME/.zshrc"
THEME="$HOME/.oh-my-zsh/themes/nagiip.zsh-theme"

# Check if file exists
if [ ! -f "$USER_FILE" ]; then
    echo -e "\n ${r}[×] Error: NAGIIP is not fully configured or usernames.txt is missing.${n}"
    exit 1
fi

CURRENT_NAME=$(cat "$USER_FILE")

echo
echo -e " ${c}             (\_/)"
echo -e "              (${y}^_^${c})     ${g}Hey dear${c}"
echo -e "             ⊂(___)づ  ⋅˚₊‧ ଳ ‧₊˚ ⋅"
echo
echo -e " [+] ${c}Current Banner Name: ${g}$CURRENT_NAME${n}"
echo

while true; do
    read -p "$(echo -e ${g}[${n}+${g}]──[${n}Enter New Name${g}]────►${n} )" name
    echo
        
        if [[ -z "$name" ]]; then
            echo -e " ${E} ${r}Name cannot be empty!${c}"
            echo
            continue
        fi

       
        if [[ ! "$name" =~ ^[a-zA-Z0-9[:space:]-]+$ ]]; then
            echo -e " ${E} ${r}Invalid Input! No fancy fonts or symbols.\n ${E} ${r}Use letters, numbers, hyphens & spaces only.${c}"
            echo
            continue
        fi

        name="${name^^}"
        name="${name// /-}"

 
        len=${#name}
        if [[ $len -ge 1 && $len -le 8 ]]; then
            break
        else
            echo -e " ${E} ${r}Name must be between ${g}1 and 8${r} characters.\n ${y}Current length is: ${g}$len${c}"
            echo
        fi
    done

# Replace the name in config files
if [ -f "$ZSHRC" ]; then
    sed -i "s/$CURRENT_NAME/$name/g" "$ZSHRC"
fi

if [ -f "$THEME" ]; then
    sed -i "s/$CURRENT_NAME/$name/g" "$THEME"
fi

# Update the record
echo "$name" > "$USER_FILE"

echo -e " ${g}[+] Banner name successfully changed to: $name${n}"
echo -e " ${y}[!] Type 'clear' or restart your terminal to see the changes.${n}"
echo
